name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: bricklife/scratch-gui
          ref: lego-bluetooth-extensions
          path: ./scratch-gui
      - run: npm ci
        working-directory: ./scratch-gui
      - uses: actions/checkout@v2
        with:
          repository: bricklife/scratch-lego-bluetooth-extensions
          ref: master
          path: ./scratch-lego-bluetooth-extensions
      - run: npm ci
        working-directory: ./scratch-lego-bluetooth-extensions
      - run: npm run register
        working-directory: ./scratch-lego-bluetooth-extensions
      - run: npm run build
        working-directory: ./scratch-gui
      - run: npm run build
        working-directory: ./scratch-lego-bluetooth-extensions
      - run: cp -r ./scratch-lego-bluetooth-extensions/build ./scratch-gui/build/xcratch
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scratch-gui/build
